#!/usr/bin/env python

# A program to allow geolocation.  Allows the detection of location information,
# the geocoding of that information and the transformation of the resulting
# geocodes.  Uses a plugin system for flexibility.
# Copyright (C) 2010 Francis Markham
# This program is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by 
# the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version. This program is distributed in the 
# hope that it will be useful, but WITHOUT ANY WARRANTY; without 
# even the implied warranty of MERCHANTABILITY or FITNESS FOR 
# A PARTICULAR PURPOSE. See the GNU General Public License 
# for more details. You should have received a copy of the GNU General 
# Public License along with this program. If not, see <http://www.gnu.org/licenses/>. 


import plugins, sys, os, optparse

def print_err(msg):
    sys.stderr.write(msg + "\n")
    sys.exit(1)

#  Detect plugins
path = os.path.abspath(os.path.dirname(sys.argv[0])) + os.path.sep
plugins_path = path + "plugins/"

if not (os.path.exists(plugins_path) and os.path.isdir(plugins_path)):
    print_err("Could not find plugins, expected at: " + plugins_path)

# Try and load plugins
plugins.load_plugins(plugins_path)

#  Parse command-line
parser = optparse.OptionParser(version="%prog 1.0")
parser.add_option("-x", "--listdetectors",
                  action="store_true", dest="list_detectors", 
                  help="List known detectors, and exit.",
                  default=False)
parser.add_option("-y", "--listlocators",
                  action="store_true", dest="list_locators", 
                  help="List known locators, and exit.",
                  default=False)
parser.add_option("-s", "--listoutspecifiers", dest="list_specifiers",
                  action="store_true",
                  help="List valid output specifiers, and exit.",
                  default=False)
parser.add_option("-t", "--type", dest="type",
                  help="Specify the type of information to geolocate " + 
                  "based on.  Currently \"wifi\", \"ip\" and \"ipself\" are supported.",
                  default=None)
parser.add_option("-i", "--info", dest="info",
                  help="Specifies the data to geolocate with.  Optional.",
                  default="auto")
parser.add_option("-d", "--detector", dest="detector",
                  help="Detector to use to find info.  Optional",
                  default="auto")
parser.add_option("-l", "--locator", dest="locator",
                  help="Locator to use to geolocate. Optional.",
                  default="auto")
parser.add_option("-o", "--outputtype", dest="outputtype",
                  help="Output type to use.  Optional.  " +
                  "Currently \"json\" and \"csv\" are supported but " +
                  "this can be extended with plugins.",
                  default="json")
parser.add_option("-f", "--outputformat", dest="outputformat",
                  help="Format specifier for csv output.  Optional.  " +
                  "Takes the form \"abcd\" where a, b, c and d are output " +
                  "format specifiers.  Run with --listspecifiers for a list.",
                  default=None)
parser.add_option("-v", "--verbose",
                  action="store_true", dest="verbose", 
                  help="Verbose output.",
                  default=False)


(options, args) = parser.parse_args()

if options.list_detectors:
    if options.verbose:
        print "Detector list:"
    for p in plugins.find_plugins():
        if plugins.Detector in p.__bases__:
            print p.name()
    sys.exit(0)
    
if options.list_locators:
    if options.verbose:
        print "Locator list:"
    for p in plugins.find_plugins():
        if plugins.Locator in p.__bases__:
            print p.name()
    sys.exit(0)

if options.list_specifiers:
    if options.verbose:
        print "Output specifiers:"
    for name, details in plugins.StandardNames.names.items():
        print "%s\t%s" % details
    sys.exit(0)


if not options.type:
    print "ERROR -- Expected Arguments not given!"
    parser.print_help()
    sys.exit(1)

outputformatter = plugins.find_plugin_by_name(options.outputtype, plugins.Formatter)
if not outputformatter:
    print_err("All could not find plugin for output formatter %s." % (options.outputtype))

inputformatter = plugins.find_plugin_by_name("json", plugins.Formatter)



# if we are automatically detecting location info
if options.info == "auto":
    if options.verbose: print "Automatically detecting info."
    
    # make sure its a valid info type
    if not options.type in plugins.StandardNames.detector_types:
        print_err("Unknown type %s" % options.type)

    # find a detector plugin that can do what we want
    detector = None
    if options.detector == "auto":
        unrunnable = []
        for p in plugins.find_plugins():
            if (plugins.Detector in p.__bases__) and (options.type in p.detection_capabilities()):
                if options.verbose:
                    print "Using detector %s" % p.name()
                detector = p()
                if detector.can_run():
                    break
                else:
                    unrunnable.append(p.name())
                    detector = None
        if not detector:
            if len(unrunnable) > 0:
                print_err("All detectors of type \"%s\" are unrunnable.  They are \"%s\"." % (options.type, ', '.join(unrunnable)))
            else:
                print_err("Could not find detector of type \"%s\"." % options.type)
                
    else:
        p = plugins.find_plugin_by_name(options.detector)
        if not p:
            print_err("Could not find a plugin \"%s\"." % options.detector)
        if not plugins.Detector in p.__bases__:
            print_err("Plugin \"%s\" is not a detector." % options.detector)
        if not options.type in p.detection_capabilities():
            print_err("Plugin \"%s\" does not detect type \"%s\"." % (options.detector, options.type))
        detector = p()
        if not detector.can_run():
            print_error("Plugin \"%s\" cannot run." % options.detector)

    if outputformatter.needs_output_specifiers() and not options.outputformat:
        print_error("To use output type \"%s\" you must specify an output format with --outputformat." %s outputformatter.name())

    detection = outputformatter.format_output(detector.detect(options.type), options.outputformat)
else:
    #if using -i option
    detection = options.info

# Fixme!
options.inputformat = None
if inputformatter.needs_input_specifiers() and not options.inputformat:
    print_error("To use input type \"%s\" you must specify an output format with --inputformat." %s inputformatter.name())

info = inputformatter.parse_input(inputformatter, options.inputformat)

locator = None
if options.locator == "auto":
    unrunnable = []
    for p in plugins.find_plugins():
        if (plugins.Locator in p.__bases__) and (options.type in p.location_capabilities()):
            if options.verbose:
                print "Using locator %s" % p.name()
            locator = p()
            if locator.can_run():
                break
            else:
                unrunnable.append(p.name())
                locator = None
    if not locator:
        if len(unrunnable) > 0:
            print_err("All locators of type \"%s\" are unrunnable.  They are \"%s\"." % (options.type, ', '.join(unrunnable)))
        else:
            print_err("Could not find locator of type \"%s\"." % options.type)
else:
    for p in plugins.find_plugins():
        if p.name() == options.locator:
            if not plugins.Locator in p.__bases__:
                print_err("Plugin \"%s\" is not a locator." % options.locator)
            if not options.type in p.location_capabilities():
                print_err("Plugin \"%s\" does not detect type \"%s\"." % (options.locator, options.type))
            locator = p()
            if locator.can_run():
                break
            else:
                print_error("Plugin \"%s\" cannot run." % options.locator)
    if not locator:
        print_err("Could not find a plugin \"%s\"." % options.locator)

location = locator.locate(options.type, info)
print location
